import type { Metadata } from "next";
import Link from "next/link";
import { StudyInformationLayout } from "../information-layout";

export const metadata: Metadata = { title: "Study guide for CBSE Classes 1–12", description: "Use Paper Shapers for chapter revision, timed mock papers, answer review, and practical study planning." };

export default async function StudyGuidePage() {
  return <StudyInformationLayout eyebrow="Study guide" title={<>A little structure<br />for the days your brain says <em>“later.”</em></>} lede="You do not have to feel ready before you begin. Pick one chapter and one kind of practice; the next step becomes much easier to see."><section className="study-information__section page-shell"><div className="guide-grid"><article><p className="kicker">Before a test</p><h2>Use a quick check.</h2><p>Choose one chapter you have already learned. Make a smaller paper, put your notes away, and answer without looking. This tells you more than rereading does.</p></article><article><p className="kicker">Before an exam</p><h2>Practise the whole rhythm.</h2><p>Use a half or full paper, set aside a real block of time, and write complete responses. Review after the session—never while you are still trying to answer.</p></article><article><p className="kicker">After a result</p><h2>Turn one miss into one task.</h2><p>Do not start by remaking everything. Find one definition, calculation, or step you missed and make your next paper a little more specific.</p></article><article><p className="kicker">When you feel stuck</p><h2>Make the brief smaller.</h2><p>One subject, one chapter, twenty minutes. A short honest attempt gives you a better starting point than waiting for a perfect plan.</p></article></div></section><section className="study-information__section page-shell info-question-list"><div><p className="kicker">What this can help with</p><h2>Questions worth asking yourself.</h2></div><ul><li>Which chapter needs another look?</li><li>Can I explain this idea without opening the book?</li><li>What does a timed attempt feel like today?</li><li>What should I practise before the next class test?</li></ul><Link className="button button--dark" href="/papershapers/tests/new">Start with one chapter →</Link></section></StudyInformationLayout>;
}
