import type { Metadata } from "next";
import Link from "next/link";
import { StudyInformationLayout } from "../information-layout";

export const metadata: Metadata = { title: "How Paper Shapers works", description: "A clear guide to building, attempting, reviewing, and saving free CBSE mock-paper practice." };

export default async function HowItWorksPage() {
  return <StudyInformationLayout eyebrow="How it works" title={<>Practice is more useful<br />when you can <em>see the next step.</em></>} lede="Paper Shapers is a free study space for CBSE Classes 9–12. It helps you turn the part of the syllabus you are studying now into a focused practice session."><section className="study-information__section page-shell"><div className="info-steps"><article><span>01</span><h2>Tell us what you are studying.</h2><p>Choose your class, subject, and mapped chapters. You do not need to write a complicated prompt or guess what to ask for.</p></article><article><span>02</span><h2>Choose the kind of practice you need.</h2><p>Try a quick check when you have twenty minutes, a half paper when you are building confidence, or a full paper when you are ready to sit longer.</p></article><article><span>03</span><h2>Write your own answers first.</h2><p>Open the paper in a calm test view, use the timer if it helps, and save your work as you go. The paper stays fixed during an attempt.</p></article><article><span>04</span><h2>Use the review to plan tomorrow.</h2><p>See the question, your response, feedback, and the answer outline together. The point is not a perfect score; it is knowing what to practise next.</p></article></div></section><section className="study-information__section study-information__section--ink"><div className="page-shell info-split"><div><p className="kicker">What stays free</p><h2>No subscription wall in the way of practice.</h2></div><div><p>Creating a study desk, making a mapped paper, attempting it, and saving a printable PDF are free. We will be direct if a future feature needs a different arrangement.</p><Link className="button button--accent" href="/papershapers/tests/new">Build a paper →</Link></div></div></section></StudyInformationLayout>;
}
