import type { Metadata } from "next";
import Link from "next/link";
import { StudyInformationLayout } from "../information-layout";

export const metadata: Metadata = { title: "Paper Shapers for teachers and coaching teams", description: "A free CBSE mock-paper workflow that supports teacher-led revision without replacing teacher judgement." };

export default async function TeachersPage() {
  return <StudyInformationLayout eyebrow="For teachers & coaching teams" title={<>Less time rebuilding<br />the same practice set. <em>More room to teach.</em></>} lede="Paper Shapers supports teacher-led revision with clear chapter choices, individual practice, downloadable papers, and a simple way to see what learners need next."><section className="study-information__section page-shell"><div className="teacher-grid"><article><span>FOR A TEACHER</span><h2>Shape practice around the class you actually have.</h2><p>Use the mapped class, subject, and chapter options to start a paper from the work your learners have covered. It is a starting point for your judgement, not a replacement for it.</p></article><article><span>FOR A COACHING TEAM</span><h2>Give every learner a private attempt space.</h2><p>Learners can create their own study desks, practise independently, save PDFs, and return to the feedback. Shared briefs and educator review are planned pilot features, not promises already switched on.</p></article><article><span>FOR A SCHOOL</span><h2>Keep the conversation practical.</h2><p>Tell us the class range, subjects, and kind of revision problem you are trying to solve. We will use that to shape a small, honest pilot conversation.</p></article></div></section><section className="study-information__section study-information__section--gold"><div className="page-shell info-split"><div><p className="kicker">Start a conversation</p><h2>Tell us what your students are finding difficult.</h2></div><div><p>Whether it is revision consistency, mock-paper preparation, or an easier way to organise practice, we want to hear the real problem before proposing a solution.</p><Link className="button button--dark" href="/papershapers/contact">Contact Paper Shapers →</Link></div></div></section></StudyInformationLayout>;
}
