import type { Metadata } from "next";
import { StudyContactForm } from "../study-contact-form";
import { StudyInformationLayout } from "../information-layout";

export const metadata: Metadata = { title: "Contact and feedback", description: "Send Paper Shapers feedback, school, coaching, or partnership enquiries." };

export default async function ContactPage() {
  return <StudyInformationLayout eyebrow="Contact & feedback" title={<>Tell us the useful bit.<br />And the <em>not-so-useful bit.</em></>} lede="We are building Paper Shapers in the open. A short note about a confusing step, a missing subject need, or a school idea is genuinely helpful."><section className="study-information__section page-shell contact-layout"><div><p className="kicker">Send a note</p><h2>We will read it.</h2><p>Use this for product feedback, school or coaching enquiries, and partnership conversations. For general Paper Shapers news, you can also find us on <a href="https://www.linkedin.com/company/papershapersai">LinkedIn</a> and <a href="https://www.instagram.com/papershapers_works/">Instagram</a>.</p><StudyContactForm /></div><aside><p className="kicker">What happens next</p><ol><li>Your note is stored securely with the Paper Shapers team.</li><li>We read it alongside other product feedback.</li><li>If you asked for a reply, we use your email only to respond.</li></ol></aside></section><section className="study-information__section page-shell"><p className="kicker">Feedback cards</p><h2>What we invite people to tell us.</h2><p className="info-disclosure">These are illustrative examples of useful feedback, not real user reviews or testimonials.</p><div className="feedback-card-grid"><article><p>“I could make the paper, but I was unsure which chapters to choose first.”</p><span>Example: Class 10 learner</span></article><article><p>“A printable version would help us use this as a small weekend practice activity.”</p><span>Example: parent or guardian</span></article><article><p>“I want to know which part of the class needs more revision after a mock.”</p><span>Example: teacher</span></article></div></section></StudyInformationLayout>;
}
